services:
  app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=inptic
      - POSTGRES_PASSWORD=inptic2024
      - POSTGRES_DB=inptic_db
      - POSTGRES_HOST=db
      - GMAIL_USER=ingridboussoyi@gmail.com
      - GMAIL_APP_PASSWORD=udeamtgnfxapsaja
      - SECRET_KEY=910faef0a4f2f106d2cc0930b2f4da70b22d2404d00479e4dd9a2953c790dc69
      - ADMIN_EMAIL=herlymba828@gmail.com
      - NOTIFICATION_EMAIL=herlymba828@gmail.com
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - monitoring

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=inptic
      - POSTGRES_PASSWORD=inptic2024
      - POSTGRES_DB=inptic_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inptic -d inptic_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:10.4.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/inptic-rh.json
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - monitoring

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge
