# ============================================================
# Jobs Jenkins — Pipeline INPTIC RH
# ============================================================
jobs:
  - script: |
      pipelineJob('inptic-rh') {
        displayName('INPTIC RH — Pipeline CI/CD')
        description('Build et déploiement automatique')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/Herlymba828/inptic-etudiants.git')
                }
                branch('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
        triggers {
          scm('H/5 * * * *')
        }
      }
